# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'TimelineKeeping' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  

  # Pods for TimelineKeeping
  pod 'Alamofire', '~> 3.4'
  pod 'TanLT1Extensions'

  target 'TimelineKeepingTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TimelineKeepingUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
