# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'TrainingImageApp' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TrainingImageApp
  pod 'Alamofire', '~> 3.4'
  pod 'TanLT1Extensions'

  target 'TrainingImageAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TrainingImageAppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
