# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'CustomerEmotion' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CustomerEmotion
  pod 'Alamofire', '~> 3.4'
  pod 'TanLT1Extensions'    

  target 'CustomerEmotionTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CustomerEmotionUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
