# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'StaffApp' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for StaffApp
  pod 'Alamofire', '~> 3.4'
  pod 'TanLT1Extensions'
  pod 'OneSignal'
  pod 'EstimoteSDK'
  
  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['SWIFT_VERSION'] = '2.3' # or '3.0'
      end
    end
  end
  
  target 'StaffAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'StaffAppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
