# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'StaffApp' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for StaffApp
  pod 'Alamofire', '~> 3.4'
  pod 'TanLT1Extensions'
  pod 'OneSignal'
  pod 'EstimoteSDK'
  pod 'RealmSwift'
  
  target 'StaffAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'StaffAppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
